version: '3.7'

services:

  # api:
  #   container_name: api
  #   restart: unless-stopped
  #   build: ./
  #   ports:
  #     - ""

  # caddy:
  #   image: caddy:2.7.4-alpine
  #   container_name: caddy-service
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - $PWD/Caddyfile:/etc/caddy/Caddyfile
  #     - $PWD/site:/srv
  #     - caddy_data:/data
  #     - caddy_config:/config

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  caddy_data:
    external: true
  caddy_config:
  mongo-data:
    driver: local