// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/YungBenn/go-twonana-portfolio/config"
	"github.com/YungBenn/go-twonana-portfolio/internal/http/handler"
	"github.com/YungBenn/go-twonana-portfolio/internal/nft"
	"github.com/YungBenn/go-twonana-portfolio/internal/cloudinary"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitNft(db *mongo.Database, env config.EnvVars) *handler.NftHandler {
	nftRepository := nft.NewNftRepository(db)
	mediaService := cloudinary.NewMediaService(env)
	nftService := nft.NewNftService(nftRepository, mediaService)
	nftHandler := handler.NewNftHandler(nftService)
	return nftHandler
}
