// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/YungBenn/go-twonana-portfolio/internal/admin"
	"github.com/YungBenn/go-twonana-portfolio/internal/http/handler"
	"github.com/gofiber/fiber/v2/middleware/session"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitAdmin(db *mongo.Database, store *session.Store) *handler.AuthHandler {
	adminRepository := admin.NewAdminRepository(db)
	adminService := admin.NewAdminService(adminRepository)
	authHandler := handler.NewAuthHandler(adminService, store)
	return authHandler
}
